[workspace]
members = [
    "mos6502",
]

[package]
name = "snes-rusty"
version = "0.1.0"
edition = "2024"

[dependencies]
lazy_static = "1.4.0" # Or the latest version
mos6502 = { path = "./mos6502"}

bitflags = "1.2.1"
sdl2 ="0.34.0" 
rand = "=0.7.3"
